# Docker compose configuration for local development

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: nginx:1.7
  links:
    - phphaproxy
    - phpfiles
  #  - memcached
  volumes:
    - .:/app:rw # TODO: Make read-only when Yii is configured properly not to write to anywhere else than under /files
    - .files:/files:rw
  ports:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
  env_file:
   - .env
  working_dir: '/app'
  command: "/app/stack/nginx/run.sh"

# HA Proxy for php service scaling
phphaproxy:
  image: neam/tutum-haproxy-awaiting-prs
  links:
    - phpha
  ports:
    # Publish stats port
    - "8088" # TODO: Switch to 1936 when using latest tutum master again
  environment:
    BACKEND_PORT: 9000
    FRONTEND_PORT: 9000
    STATS_AUTH: stats:stats
    MODE: tcp
    TIMEOUT: connect 5000, client 50000, server 50000

# The highly available php service for interpreting php code without access to /files
phpha:
  image: neam/dna-project-base-debian-php:5.6.13-fpm-0.4.0
  links:
    - mailcatcher
    - redisphpsessionhandler
    - localdb
  #  - memcached
  volumes:
    - .:/app:rw # TODO: Make read-only when Yii is configured properly not to write to anywhere else than under /files
  ports:
    - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'on'
    XDEBUG_DEFAULT_ENABLE: 'off'
    RUNNING_LOCALLY: '1'
    EXCLUDE_PORTS: 22
  env_file:
    - .env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

redisphpsessionhandler:
  image: redis

# The single-node php service for interpreting php code with read-write access to user-generated files
# (to support file uploads and other local file manipulations)
phpfiles:
  image: neam/dna-project-base-debian-php:5.6.13-fpm-0.4.0
  links:
    - mailcatcher
    - redisphpsessionhandler
    - localdb
  #  - memcached
  volumes:
    - .:/app:rw # TODO: Make read-only when Yii is configured properly not to write to anywhere else than under /files
    - .files:/files:rw
  ports:
    - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'on'
    XDEBUG_DEFAULT_ENABLE: 'off'
    RUNNING_LOCALLY: '1'
    EXCLUDE_PORTS: 22
  env_file:
    - .env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

# Local database server to mimic a cloud database
localdb:
  image: mysql:5.6.27
  volumes:
    - ./stack/localdb/.db/mysql:/var/lib/mysql:rw
    - ./stack/localdb/:/stack/localdb:rw
  ports:
   - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: "local-mysql-pass"
  command: "/stack/localdb/run.sh"

# Memcached server for serving cached contents via the nginx-memcache plugin
#memcached:
#  image: memcached:1.4.22
#  ports:
#    - "11211"

# Mailcatcher server for catching outgoing email when not in production
mailcatcher:
  image: nisenabe/mailcatcher
  ports:
    - "25"
    - "1080"

# A container to run builder commands locally
builder:
  #build: vendor/neam/docker-stack/base-images/php-app-builder/
  image: neam/php-app-builder:0.4.0
  volumes:
    - .:/app:rw # TODO: Make read-only when Yii is configured properly not to write to anywhere else than under /files
    - .files:/files:rw
    - ../set-deployment-target.inc.sh:/set-deployment-target.inc.sh
    - ../.git:/.git
    - ~/.composer:/root/.composer
    - ~/.ssh:/root/.ssh:ro
  working_dir: '/app'
  command: "true"

# A container to run tester commands locally - start a shell by running stack/tester-shell.sh
tester:
  #build: vendor/neam/docker-stack/base-images/php-app-tester/
  image: neam/php-app-tester:0.4.0
  links:
    - web
    - localdb
  volumes:
    - .:/app:rw # TODO: Make read-only when Yii is configured properly not to write to anywhere else than under /files
    - .files:/files:rw
  working_dir: '/app'
  command: "true"

# A container to run worker/administration commands locally - start a shell by running stack/shell.sh
worker:
  #build: vendor/neam/docker-stack/base-images/php-app-worker/
  image: neam/php-app-worker:0.4.0
  links:
    - localdb
  volumes:
    - .:/app:rw # TODO: Make read-only when Yii is configured properly not to write to anywhere else than under /files
    - .files:/files:rw
  working_dir: '/app'
  command: "true"

# A container that is linked to and thus can output linked information about running containers locally
info:
  image: debian:jessie
  volumes:
    - .:/app:rw # TODO: Make read-only when Yii is configured properly not to write to anywhere else than under /files
    - .files:/files:rw
  links:
    - web
    - phphaproxy
    - phpha
    - phpfiles
    - builder
    - tester
    - worker
    - localdb
  #  - memcached
  working_dir: '/app'
  command: "true"

# Selenium...
