<?php
// Warning: If you add/remove any languages from this list,
// make corresponding changes to languageDirections and LanguageHelper::getTranslatedLanguageList()

// This list is used directory by vendor libraries, and the format cannot therefore be changed.
return $languages = array(
    // Default language
    'en' => 'English',
    // Translation languages
    'ar' => 'العربية',
    'bg' => 'Български',
    'ca' => 'Català',
    'cs' => 'Čeština',
    'da' => 'Dansk',
    'de' => 'Deutsch',
    'en_gb' => 'UK English',
    'en_us' => 'US English',
    'el' => 'Ελληνικά',
    'es' => 'Español',
    'fa' => 'فارسی',
    'fi' => 'Suomi',
    'fil' => 'Filipino',
    'fr' => 'Français',
    'he' => 'עברית',
    'hi' => 'हिंदी',
    'hr' => 'Hrvatski',
    'hu' => 'Magyar',
    'id' => 'Bahasa Indonesia',
    'it' => 'Italiano',
    'ja' => '日本語',
    'ko' => '한국어',
    'lt' => 'Lietuvių',
    'lv' => 'Latviešu valoda',
    'nl' => 'Nederlands',
    'no' => 'Norsk',
    'pl' => 'Polski',
    'pt' => 'Português',
    'pt_br' => 'Português (Brasil)',
    'pt_pt' => 'Português (Portugal)',
    'ro' => 'Română',
    'ru' => 'Русский',
    'sk' => 'Slovenský',
    'sl' => 'Slovenščina',
    'sr' => 'Српски',
    'sv' => 'Svenska',
    'th' => 'ไทย',
    'tr' => 'Türkçe',
    'uk' => 'Українська',
    'vi' => 'Tiếng Việt',
    'zh' => '中文',
    'zh_cn' => '中文 (简体)',
    'zh_tw' => '中文 (繁體)',
);
