# Docker compose configuration for docker-cloud node newrelic agent

newrelic:
  image: 'tutum/newrelic-agent:latest'
  deployment_strategy: every_node
  environment:
    - HOSTNAME=$DOCKERCLOUD_NODE_HOSTNAME
    - 'NEW_RELIC_LICENSE_KEY=1234567890afaefaefaefaef1234567890afaefaefaefaef'
  net: host
  pid: host
  privileged: true
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/dev:/dev'
    - '/sys:/sys'
