# Docker compose configuration for docker-cloud node syslogger

syslogger:
  image: 'tutum/syslogger:latest'
  command: 'syslog://logs2.papertrailapp.com:55555'
  deployment_strategy: every_node
  environment:
    - HOSTNAME=$DOCKERCLOUD_NODE_HOSTNAME
  restart: always
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock'
