# Docker compose configuration for production docker-host deployment

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: tutum.co/%TUTUM_USER%/%REPO%-nginx:git-commit-%COMMITSHA%
  links:
    - phphaproxy
    - phpfiles
#    - memcached
  volumes_from:
    - phpfiles
  ports:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
    VIRTUAL_HOST: %VIRTUAL_HOST%
  env_file:
   - %ENV_FILE_DIR%/.env
  working_dir: '/app'
  command: "/app/stack/nginx/run.sh"

# HA Proxy for php service scaling
phphaproxy:
  image: neam/tutum-haproxy-awaiting-prs
  links:
    - phpha
  ports:
    # Publish stats port
    - "8088" # TODO: Switch to 1936 when using latest tutum master again
  environment:
    BACKEND_PORT: 9000
    FRONTEND_PORT: 9000
    MODE: tcp
    TIMEOUT: connect 5000, client 50000, server 50000
    # Some sort of protection for the stats endpoint (needless to say, you should use a unique secure password in production)
    STATS_AUTH: stats:n3v3rg0nnAg1v3y0uup

# The elastically scalable php service for interpreting php code without access to /files
phpha:
  image: tutum.co/%TUTUM_USER%/%REPO%-php:git-commit-%COMMITSHA%
  links:
    - mailcatcher
    - redisphpsessionhandler
#    - memcached
  ports:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'off'
  env_file:
   - %ENV_FILE_DIR%/.env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

redisphpsessionhandler:
  image: redis

# The single-node php service for interpreting php code with read-write access to user-generated files
# (to support file uploads and other local file manipulations)
phpfiles:
  image: tutum.co/%TUTUM_USER%/%REPO%-php:git-commit-%COMMITSHA%
  links:
    - mailcatcher
    - redisphpsessionhandler
#    - memcached
  ports:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'off'
  env_file:
   - %ENV_FILE_DIR%/.env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

# Memcached server for serving cached contents via the nginx-memcache plugin
#memcached:
#  image: memcached:1.4.22
#  ports:
#    - "11211"

# Mailcatcher server for catching outgoing email when not in production
mailcatcher:
  image: nisenabe/mailcatcher
  ports:
    - "25"
    - "1080"

# Selenium...
